#I create a variable 'DNA' with the DNA code.
DNA = 'ACTGTGCTGACTCCCGGTGCTGCCGCTGCCATAGCTAAAGCCCGGGTCCTGGTAGGCAGGCGGGAAGCAG \
GGTGGGGGTCCCGGGTACTGGTAGGGGTAGCCCTGACCCAGAGGCGGGGGGGCAGCCGGGTGGGGCAGCG \
GGGCCAGCGTGTCCTGAA-CGAAGTCCCACTGGAGCCACTGTTGAGGTTCAGGGTGGCGAGATCTGGCGG \
NNNAGGGTAGGTGAGGGCCGCGGAGGGGCCTCCGGCGTTCCCCTCCCCCCCGCCCTGAAACCCGAAGCCC \
CCACTCACTGCTGCAGAGATCCCCTGAAAACGTAGTAGCACTGCTCgagacAGGTGATCTGTTGACCTGA \
AACCGCAGGAAGCCGTGCTTCAGCAAGCTGCTGGCGTACTTCCGGGCCT---GCCGCTCCTTGAAGCCCT \
CCACGTGTGTGTACAGCCAGTCCACCACGTCCGCCCCTGGCCGGCACCAGCGGTCAGCCCGCAGCCTCGA \
GGCAAGCAGCCCTGCCNNTGGCACTATCCGC-CGCGGGGACGGCCACTCACCGATGACGGCATNNGCGAT \
GGTGATCTTGAGCCACATGCGGTCGCGGATCTCCAGTCCCGAG---GGCAGCTGCATGACCCGGACGACG \
GCGCTCATGTCACtcaccgtcagcggcgcctcttccagCCAGCTCTGCAAAGCACAGACAGCCCCGCTTC \
GCCCCAGCATCTGAAAGCGGGGGACTCggcAcgCTGCACCCCCAGGGGAGCCTCTGGGCAGAGCCTGCGC \
CAGGGCGCAAGCTGGACGGTGCGTGACAGCAGGGCCCCGGCCCACTGCAGGATGCACCCCCGTGAGGCTG \
GGGCGTGAGCAGGGGGGTTGGACAtttAGTCTCCCACTTCTACAGACACTTTTCATCAGGATCCTAGGCA \
CAAACTGGGCTGAAACCCCACCCTGCAGACCAGGAAGTAATGAGAACAGGGCAGGCCCCTTCCCCTCNNC \
GCATGCC-CACCCGAGAGCGCAGGCTGTTAGTCGTGTTAATGGCAGGAAGCAGAATGGAGACCTGGCCCC \
TGCCTCTGAA-CCGTGGGTGCTCaactggctaGCCCTACGTACATCCCCTGTTCcggCCAACACACAGAC \
ATGAGCAGGATGGGCTGCACAAGGTGGGCACGGGTGCCTGTGCACACGTCTGTGCAGGGAGTTGGGGACA \
GGCAACACACACGTGTCACAGCCCCATGACGGggcaattgcGCCATGCTGGCTGAATGGCAGAGACGCCC \
CTCCAAGCCTCGGTTTCTGCTGGGGCCCTCAGGAGCTGCCACTTACGTGGAGCACCAGGCACGGAGCTGG \
TTAGTGAGGAGGAGCTGGTGCGCGTGACGGCGCTGGAGCAGGGACTCGTACCGTAGCGGGGCAGGGCNNN \
TGTCAGTGCCGCCGTGTGGtcagcggcgatCGGCG-GGTCGATGGGCCGCACCGGGTCAGCTGGGTGNAG \
ACACGTGGCGATGACAGGCGGACAGATGGACAGGGTGGGAGGGCAGGGTGCAGGGCACAGAGGAGAGAGG \
CCTTCAGGCTAGGTAGGCGCCCCCTCCCCATCCCGccccGTGTGCCCCGAGGGCCACTCACCCCGTGGGA \
CGGTGAAGTAGCTTCG-GGCGTTGGGTCCAGCACTTGGCCACAGTGAGGCTGNAAATGGCTGCAGGAACG \
GTGGTCCCCCCGCAAGGCCCCCATGGTCCCACCTCCCTGCCTGGCCCCTCCCGCTCCAGCGCCNCCAGCC'

DNA = DNA.replace(' ', '')
DNA = DNA.upper()

#I check how many times A, D, G, T appear in the DNA code.
A = DNA.count('A')
C = DNA.count('C')
G = DNA.count('G')
T = DNA.count('T')

print('\nAdenina pojawia sie ' +str(A) + ' razy.')
print('Cytozyna pojawia sie ' +str(C) + ' razy.')
print('Guanina pojawia sie ' +str(G) + ' razy.')
print('Tymina pojawia sie ' +str(T) + ' razy.\n' )

#I count how many times 'GAGA' appears in the code.
GAGA = DNA.count('GAGA')
print('Sekwencja GAGA pojawia sie ' + str(GAGA) + ' razy.')

#I erase all the "N" letters from the DNA code.
DNA = DNA.replace('N', '')

#I replace 'GAGA' with 'AGAG' and count it to check if the code is correct.
DNA = DNA.replace('GAGA', 'AGAG')
AGAG = DNA.count('AGAG')
print ('Sekwencja AGAG pojawia sie ' + str(AGAG) + ' razy.\n')

#I check where in the DNA code there are 7 guanines in row.
G_7 = DNA.find('G'*7)
print('Indeks w lancuchu siedmiu guanin pod rzad to ' + str(G_7) + '.')

#I check where in the DNA code there are 6 citosines in row counting backwards.
C_6 = DNA.rfind('C'*6)
print('Indeks w lancuchu siedmiu cytozyn pod rzad to ' + str(C_6) + '.\n')

#I count how many times in the DNA code there is the sequence CTGAAA.
CTGAAA = DNA.count('CTGAAA')
print('Sekwencja CTGAAA wystepuje ' + str(CTGAAA) + ' razy.')

#I count how many CTGAAA there are together with its possible mutations CTGAA-.
mut_CTGAAA = DNA.count('CTGAA-')
num_CTGAAA_ = int(CTGAAA) + int(mut_CTGAAA)
print ('Sekwencja CTGAAA wraz z mozliwymi mutacjami wystepuje ' + str(num_CTGAAA_) + ' razy.\n')

#I clear the DNA out of any errors.
DNA = DNA.replace('-','')

#I create RNA replacing thymine (T) with uracil (U).
RNA = DNA.replace('T','U')
print(RNA)